package cemc.s3;

import static org.junit.Assert.*;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;

import org.junit.Test;

public class NeedleSearchTest {

	@Test
	public void testGetTotalOcc_1_01() {
		String needle ="aab";
		String hays = "abacabaa";
		int total  = NeedleSearch3.getTotalOcc(needle, hays);
		assertEquals(total, 2);
		System.out.println(total);
	}
	
	@Test
	public void testGetTotalOcc() {
		String needle ="abc";
		String hays = "bcbac";
		int total  = NeedleSearch3.getTotalOcc(needle, hays);
		assertEquals(total, 2);
		System.out.println(total);
	}

	@Test
	public void testGetTotalOcc_1_02() {
		String needle ="xxxxxxxx";
		String hays = "nddyhsslitxxroowyofmboanirdoepueroerhrczfrpdijhxtsgzgtpzobsgricmgoqtftdctvusddsvsopztbdpbxgxcybpctclvhyuedorzrwmpzifvtnphrvwdwbovlexaxnwkgtodzlewplvurnjcedfisiapenjlhexogyeexxruupymvgsufmvpklhujnautur";
		int total  = NeedleSearch3.getTotalOcc(needle, hays);
		assertEquals(total, 0);
		System.out.println(total);
	}

	@Test
	public void testGetTotalOcc_1_03() {
		String needle ="gggggggg";
		String hays = "pilqbbvitbcnyzadvlqlsvdxagwxkvwwqoponfhiqbynwmsfontjjvlgegnfxgggggggggtnjmwbxzhwlggggggggndwvizzkwoxfmwqtmgbwbsrnqoxfrltkcvaerokapmzuhohaggggggggwucpotxkggggggggdmsoinzgdwyavvttixlvheixjzxmiqwvzopjvmo";
		int total  = NeedleSearch3.getTotalOcc(needle, hays);
		assertEquals(total, 1);
		System.out.println(total);
	}
	
	@Test
	public void testGetTotalOcc_2_04() {
		String needle ="ffxewmweexpmiipfmfgw";
		String hays = "fwfewpmegeiwfmipxmxffefppfemifxgmmewxwiwkmnerxcholtimemipxgewifewfmpfxfwnfemefmppxwfwiiefmwfxgtvwfiiwpegfexmwmxmffpeinpskbjazpvfwxwegieffmwxmpfmpeihrzx";
		int total  = NeedleSearch3.getTotalOcc(needle, hays);
		assertEquals(total, 7);
		System.out.println(total);
	}
	
	@Test
	public void testGetTotalOcc_1_05() {
		String needle ="ggggggll";
		String hays = "lglgggggvqglnuzjvtvitezoymuiytggggllggsamztqrfoslgggglggqtrsinggllggggmetbkhxhskglgggglglgetqwoaggglgggljjgisojggllgggggggllkrmilgggglgghgeajxqasaolgggglggdurlgggglggnqcggggllggvfmftggggggllbgwgidifqt";
		int total  = NeedleSearch3.getTotalOcc(needle, hays);
		assertEquals(total, 10);
		System.out.println(total);
	}
	
	@Test
	public void testGetTotalOcc_1_06() {
		String needle ="ggguuuug";
		String hays = "sygofjuguuggguguguuuggaxbcvutqwliguugguugetmdgguugugguguguguuugggguuuguggugcugguuugugguuguughlnnqnbgguguuugmuugguuggpuclvuugguuggnulhsuauggguuguzguugugguuggugugugugugugxbtffxbuggguugupuguugggugguguuug";
		int total  = NeedleSearch3.getTotalOcc(needle, hays);
		assertEquals(total, 28);
		System.out.println(total);
	}
	
	@Test
	public void testGetTotalOcc_2_22() {
		String needle ="vtseeeevtseeeevtseeeevtseeeevtseeeevtseeeevtseeeevtseeeevtseeeevtseeeevtseeeevtseeeevtseeeevtseeeevtseeee";
		String hays = "esveeesesvteettvseeeetvseeeetveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseeveetseevee";
		int total  = NeedleSearch3.getTotalOcc(needle, hays);
		assertEquals(total, 11);
		System.out.println(total);
	}
	
	@Test
	public void testGetTotalOcc_3_06() {
		String needle ="lllllqlqllqllqlqllqqlqqqlllllqlqqlqllqqqqqqqqllllqqqqllqqqlqllqlqqqlllqqlqllqqlqqqlqlqllqqllqqlqqqllllqqqlqlqlqllqqlllqlllqlllllqqqqqqqlqlqqqlqlqqqqqllqllllqlqlqqqlqqqqqqqqqlllqqllqllllqqlqlqllqqqlqqllqqqllqlqllqqlqqqqllllqqqlqllqlqllllllllqlqlllqqqllllllqlqqlqqqqqqqlqqlqqqqllqqlqqlqlqqlllqqqllqlllqqqlllqllqlllqqllqlqqqqlqqqlqqlqllllqqllllqllqlqlqqqlqqqlqllqqqqlllllllllllqqllqqlllllqlllllllqlqlqqlqlqqqlllqllqlllllqlqlqlqlllqlqllqlqlqqlqlqqqqlllqlqlqqllqlqqqqqllqlqqqqlqqqqqlllllqlqlqqqqqllqlqqlqqqlqqqlllqlllqqlqlllqllllqlqqqqqlllqqqqllqqqqlllqlqqqqqqqllqlqlllqqlqqqlqqlllllqqllqqlqllllqqlllqlllqqlqqlqqllllqlqqqlllllqlqqllqqlqlllqlqqqqllqlllqllllqllllqlllqqlqqllllllqqllqqlqllqlqllqlllqqqqlllqllqllqqlllllqllqlqlllqllllqqqqqqqlqllqlqlqqllqllllqlqqlqqqqqqlqlqqqqqllllqqqqqqqqllqqlqllqllqlqqlqqqlq";
		String hays = "mnourcvdtluxjunoftzicjmifiiazreoueouylnqiuefsgvbgcwfktamqlzdikijewhyxhpypxhxiwiehlrppglgwjuaksfzljxyaqmzgpxqcwriyjvwoaauykyrlwdxdwlsclemadmfrmtoygmdszdwkupikwtajlggmfluskvcfamrfudtbqukeexugqddicaefiozkdtddwymfsdexmzaybeotfzlydtwfjzfasgdsuqpxneyfnedcdvlfowpzscxkeyrmdswslxjijycwnnzqqllllqqlllqqqlqqqqqllqlqlqqqlqlqqqqlllqqlqqqlqqlqqqqllqqlqlllqllllqlqlllllqqqqlqqqlqqqqlqqqlqlqllqlqlllqqlqlllqlqqqlqlqqqlqlqlqllqqqqlqqqqlqqqlllllqqllqqlqqlqllqqqlllllqqqqlqlqlqlqqllqllllqqqqlqqlllllqllllllllqqqqlqqqqlqqlqqlqqqlqqlqqlllqllllqqqqlqqlqqqlqlqqqqllllllllqllqqlqqqqqllqqllqlqqlqqlllllllllqlqlqlqlqqqllqqllqlqlqqllqqlqllqlllqllllqllllllllllqqqllqqlllqlqlqlqllqlqlllqqqqllllqllllllqlqqqlllqqlqlllqlqqlllqlqqlqlqlllqqlqlllllqlqlqlllllqllqlqqqqqqlqqqqlqlqqqqllllqllqqqqqllqqqqllllqqlqqqlqqqlqqlqqlqqqqllllqqqlllqllllllqqqqlqqqqlllllqllqqlqqqqqlqqqlllqlllllqqllllqqlllllqlllqqlqllqlqlqlllqlllqqqllllqqllllqqqllqlqlllqqlllqlqllqlllqqqlqqlqqllllqllqqlqlllqlqqlqllllqqllqqqlqqlqllqqlllqlqqqqqqqqllqqqlqqqlqlqlllllqqlllqqqlqlqlqllllqqqqqllqlqlqllqqlqqqqllqqqllqllqqlllqqqlqllqqllqllqlllqlqqqqqqqajbplxdtxhsrqlpkovmnlfpyostbmtitjpdguglntfllwpaeezpzrjobvrufnbegltdkyawmmyvjhjdpyxbopyxomtycywyekfzexqmjfzlphmlaxdngmonbkahffzwfldifmlpsudqdshqymobmizchnpghabnrbtklemqflcgxfhlblznngdmvnkkchdxjuaqspgybrmltrpucasanzvywvhvaekyexytvtsraciawidnxwznsreigovxsfpnxvuthtqmlxoqivyikutusuecdadcjtgxsvyeyeazbgqrgkkzeeftyssudsrdvrpkxmwjlavkycszivfgcqxydabetqbvifdwbvpkarqyeaijoqcgehntinjwakvathgmmayrnqreafmaybgdqnkgxvwfovjpnuxfrqgsbgvxfmbmmwlaxtfmetiuyyjasqjjynththwtvofbomimeoibqgejspmpkgeedqrwqziiavxirxpfnqrpxsfoaiymutmfstsabzuazsqgpnsrupzhuftcqavxfhglrkhznkxohoypvftmqwayurdbeesutulagtncxsbxkpfdbgqbaadofbueqfqgmjnukcui";
		int total  = NeedleSearch3.getTotalOcc(needle, hays);
		assertEquals(total, 1);
		System.out.println(total);
	}
	
	@Test
	public void testGetTotalOcc_3_38() {
		String needle ="fnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnn";
		String hays = "klraaipbtpdfnnnfnnnfnnnfnnnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnnfnnn";
		int total  = NeedleSearch3.getTotalOcc(needle, hays);
		assertEquals(total, 276);
		System.out.println(total);
	}

	
	@Test
	public void testGetTotalOcc_3_43() {
		String needle ="tgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssctgggssc";
		String hays = "gssggctgssgggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgstggscgsgtsgcgsgtsgcgsgtsgcgsgtsgcgsgtsgcgsgtsgcgsgtsgcgsgtsgcgsgtsgcgsgtsgcgsgtsgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcgggsstcggggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstgscggstcgggsstcgggsstcgggsgcstggsgcstggsgcstggsgcstggsgcstggsgcstggsgcstggsgcstggsgcstggsgcstggsgcstssgcggtssgcggtssgcggtssgcggtssgcggtss";
		int total  = NeedleSearch3.getTotalOcc(needle, hays);
		assertEquals(total, 110);
		System.out.println(total);
	}
	
	// @Test  need about 16GB memory, so disable it
	public void testGetTotalOcc_4_38() throws NumberFormatException, IOException {
		String file = getFilePathFromClassPath("s3.4-38.in");
		
		FileReader fr = new FileReader(file);
		BufferedReader br = new BufferedReader(fr);

		String needle =br.readLine();
		String hays = br.readLine();
		br.close();
		int total  = NeedleSearch3.getTotalOcc(needle, hays);
		assertEquals(total, 61538);
		System.out.println(total);
	}
	
	private String getFilePathFromClassPath(String file) {
		URL url = this.getClass().getResource(file);
		return url.getFile();
	}

	
	
	
	

}
