package com.justa.springboot.api;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.justa.springboot.db.BeanRepository;
import com.justa.springboot.model.TestBean;

@Controller 
@RequestMapping(path = "/api/beans") 
public class TestBeanController {
	
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private BeanRepository beanRepository;
	
	@GetMapping(path = "/all")
	public @ResponseBody Iterable<TestBean> getAllUsers() {
			// This returns a JSON or XML with the users
		return beanRepository.findAll();
	}
}
