package com.justa.springboot.api;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.justa.springboot.db.PositionEnum;
import com.justa.springboot.db.UserManager;
import com.justa.springboot.db.UserRepository;
import com.justa.springboot.model.User;
import com.justa.springboot.service.ComplianceService;

// it comes from https://spring.io/guides/gs/accessing-data-mysql/

@Controller // This means that this class is a Controller
@RequestMapping(path = "/api/users") // This means URL's start with /users (after Application path)
public class UserController {
	
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	@Autowired
	private UserManager userManager;
	
	@Autowired
	private ComplianceService cs;

	@PostMapping(path = "/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser(@RequestBody User user) {
			// @ResponseBody means the returned String is the response, not a view name

		userManager.saveUser(user);
		return "Saved";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<User> getAllUsers() {
			// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
	
	@GetMapping(path = "/query")
	public @ResponseBody List<User> getUserByNameAndPosition(
			@RequestParam(name = "name") String name, 
			@RequestParam(name = "position") PositionEnum position) {
		
		// here position must be enum.name(), other wise it will throw ConversionFailedException
		// So you can define customized converter by implementing Converter interface  : 
		//    https://www.baeldung.com/spring-enum-request-param
		
		return userManager.getUserByNameAndPosition(name, position);
	}
	
	
	@GetMapping(path = "/complianceList", produces={"application/json"})
	public @ResponseBody String getComplianceList() {
			// This returns a JSON or XML with the users
		String[] list =  cs.getUserList();
		StringBuilder sb = new StringBuilder();
		for(String s :  list) {
			sb.append(s).append(",");
		}
		return "{\"list\":\""+ sb.toString()+ "\"}";
	}
	
	
}
